import Atlas.Specs.OperatorTheory.UnitaryGroup
import Mathlib.Analysis.CStarAlgebra.Exponential
import Mathlib.Analysis.SpecialFunctions.Exponential
import Mathlib.Analysis.Calculus.Deriv.Comp

/-!
# The one-parameter unitary group generated by a bounded self-adjoint operator (P2.3g)

For a *bounded* self-adjoint operator `A : H →L[ℂ] H` this file constructs the strongly
continuous one-parameter unitary group `U t = exp(I · t • A)` and identifies its Stone
generator with `A` itself (as a `LinearPMap` of total domain).

* `boundedGenerator A hA : OneParameterUnitaryGroup H` — the group `t ↦ exp(I · t • A)`,
  built from `selfAdjoint.expUnitary`.
* `boundedGenerator_generator : (boundedGenerator A hA).generator = A.toLinearMap.toPMap ⊤`
  — the special (bounded, everywhere-defined) case of Stone's theorem forward half. The
  domain is everything (every orbit is entire) and the value is `A`.
* `boundedGenerator_isSelfAdjoint` — the sanity check that this generator is a
  self-adjoint `LinearPMap`, consistent with `StoneTheoremForward`.

This is the concrete/bounded warm-up for the general (unbounded) Stone construction
`StoneTheoremConverse`, which requires the spectral theorem.

## Sources

* M. Reed, B. Simon, *Methods of Modern Mathematical Physics. I* (1980), §VIII.4,
  Thm VIII.7. The bounded case is elementary (no spectral theorem needed): the orbit
  `t ↦ exp(I · t • A) x` is an everywhere-convergent power series.
-/

open OperatorTheory Complex NormedSpace
open scoped Topology

-- The real module structure on `selfAdjoint (H →L[ℂ] H)` (used by `selfAdjoint.expUnitary`)
-- is a deep instance; give typeclass synthesis a larger budget for this file.
set_option synthInstance.maxHeartbeats 400000

noncomputable section

namespace OperatorTheory

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
variable (A : H →L[ℂ] H) (hA : IsSelfAdjoint A)

/-- The bounded self-adjoint `A`, packaged as an element of the `selfAdjoint` subtype. -/
private def selfAdjointElt : selfAdjoint (H →L[ℂ] H) := ⟨A, selfAdjoint.mem_iff.mpr hA⟩

/-- The one-parameter unitary group `U t = exp(I · t • A)` generated by a bounded
self-adjoint operator `A`, built from `selfAdjoint.expUnitary`. -/
def boundedGenerator : OneParameterUnitaryGroup H where
  toFun t := selfAdjoint.expUnitary (t • selfAdjointElt A hA)
  map_zero_eq_one' := by
    have hz : (0 : ℝ) • selfAdjointElt A hA = 0 := by
      ext; simp [selfAdjoint.val_smul]
    rw [hz, selfAdjoint.expUnitary_zero]
  map_add_eq_mul' s t := by
    have hc : Commute (↑(s • selfAdjointElt A hA) : H →L[ℂ] H) ↑(t • selfAdjointElt A hA) := by
      simp only [selfAdjoint.val_smul, selfAdjointElt]
      exact ((Commute.refl A).smul_left s).smul_right t
    have hsplit : (s + t) • selfAdjointElt A hA
        = s • selfAdjointElt A hA + t • selfAdjointElt A hA := by
      ext; simp [selfAdjoint.val_smul, add_smul]
    rw [hsplit, Commute.expUnitary_add hc]
  continuous_apply' x := by
    have hcont : Continuous fun t : ℝ ↦ (exp (t • (I • A))) x :=
      (ContinuousLinearMap.apply ℂ H x).continuous.comp
        (differentiable_exp_smul_const ℝ (I • A)).continuous
    refine hcont.congr fun t ↦ ?_
    simp only [selfAdjoint.expUnitary_coe, selfAdjoint.val_smul, selfAdjointElt, smul_comm I t A]

/-- The underlying operator of `boundedGenerator A hA` at time `t` is `exp(t • (I • A))`. -/
theorem boundedGenerator_coe (t : ℝ) :
    ((boundedGenerator A hA) t : H →L[ℂ] H) = exp (t • (I • A)) := by
  show (selfAdjoint.expUnitary (t • selfAdjointElt A hA) : H →L[ℂ] H) = _
  rw [selfAdjoint.expUnitary_coe, selfAdjoint.val_smul, selfAdjointElt, smul_comm]

/-- The orbit `t ↦ exp(I · t • A) x` has derivative `I • A x` at `0`
(the differential form `(d/dt)|₀ (U t x) = I • A x`). -/
theorem boundedGenerator_hasDerivAt (x : H) :
    HasDerivAt (fun t : ℝ ↦ ((boundedGenerator A hA) t : H →L[ℂ] H) x) (I • A x) 0 := by
  have hexp : HasDerivAt (fun t : ℝ ↦ exp (t • (I • A))) (I • A) 0 := by
    simpa using hasDerivAt_exp_smul_const (𝕂 := ℝ) (I • A) 0
  have hL : HasFDerivAt (⇑((ContinuousLinearMap.apply ℂ H x).restrictScalars ℝ))
      ((ContinuousLinearMap.apply ℂ H x).restrictScalars ℝ) (exp ((0 : ℝ) • (I • A))) :=
    ContinuousLinearMap.hasFDerivAt _
  have heval := HasFDerivAt.comp_hasDerivAt 0 hL hexp
  have horbit : (fun t : ℝ ↦ ((boundedGenerator A hA) t : H →L[ℂ] H) x)
      = fun t : ℝ ↦ (exp (t • (I • A))) x := by
    funext t; rw [boundedGenerator_coe]
  rw [horbit]
  exact heval

/-- **Bounded case of Stone's theorem (forward).** The Stone generator of the group
`t ↦ exp(I · t • A)` generated by a bounded self-adjoint `A` is `A` itself, with total
domain. -/
theorem boundedGenerator_generator :
    (boundedGenerator A hA).generator = A.toLinearMap.toPMap ⊤ := by
  apply LinearPMap.ext
  · rw [OneParameterUnitaryGroup.generator_domain, LinearMap.toPMap_domain,
      Submodule.eq_top_iff']
    exact fun x ↦ ⟨I • A x, boundedGenerator_hasDerivAt A hA x⟩
  · intro x _ _
    have h := (boundedGenerator A hA).generator_apply_of_hasDerivAt
      (boundedGenerator_hasDerivAt A hA x)
    rw [LinearMap.toPMap_apply, ContinuousLinearMap.coe_coe]
    calc (boundedGenerator A hA).generator ⟨x, _⟩
        = -Complex.I • (Complex.I • A x) := h
      _ = A x := by rw [smul_smul, neg_mul, Complex.I_mul_I, neg_neg, one_smul]

/-- Sanity check: the bounded generator is a self-adjoint `LinearPMap`, consistent with
`StoneTheoremForward`. -/
theorem boundedGenerator_isSelfAdjoint :
    IsSelfAdjoint (boundedGenerator A hA).generator := by
  rw [boundedGenerator_generator]
  have hdense : Dense ((⊤ : Submodule ℂ H) : Set H) := by
    rw [Submodule.top_coe]; exact dense_univ
  have hbridge := A.toPMap_adjoint_eq_adjoint_toPMap_of_dense hdense
  rw [IsSelfAdjoint.adjoint_eq hA] at hbridge
  exact hbridge

end OperatorTheory
